#ifndef SUBMENUS_H_INCLUDED
#define SUBMENUS_H_INCLUDED

// Submenus usuario
#define SM_LOGIN 0
#define SM_MENU_PRINCIPAL 1
#define SM_BUSCAR_PELICULA 2
#define SM_FAVORITOS 3
#define SM_MOSTRAR_PELICULAS 4
#define SM_INFO_PELICULA 5
#define SM_INFO_COMENTARIOS 6

// Submenus admin
#define SM_BAJA_USUARIO 100
#define SM_BAJA_PELICULA 101


#endif // SUBMENUS_H_INCLUDED
